server:
  port: 8180

logging:
  level: # change to DEBUG to see encoded / decoded payloads and extra log/console messages
    org.springframework.http.codec.json.Jackson2JsonEncoder: INFO
    org.springframework.http.codec.json.Jackson2JsonDecoder: INFO
    io.maia.reactorplayground.brandservice.services: INFO

brand:
  ford:
    random: true
    max-response-time-in-millis: 1000
    max-cars-per-search: 50

  gm:
    random: true
    max-response-time-in-millis: 1000
    max-cars-per-search: 75

  fiat:
    random: true
    max-response-time-in-millis: 1000
    max-cars-per-search: 100

  volkswagen:
     random: true
     max-response-time-in-millis: 1000
     max-cars-per-search: 120
