server:
  port: 8180

logging:
  level: # change to DEBUG to see encoded / decoded payloads
    org.springframework.http.codec.json.Jackson2JsonEncoder: INFO
    org.springframework.http.codec.json.Jackson2JsonDecoder: INFO

brand:
  ford:
    random: false
    max-response-time-in-millis: 0
    max-cars-per-search: 50

  gm:
    random: false
    max-response-time-in-millis: 0
    max-cars-per-search: 1000

  fiat:
    random: false
    max-response-time-in-millis: 0
    max-cars-per-search: 100

  volkswagen:
     random: false
     max-response-time-in-millis: 0
     max-cars-per-search: 120
